before_script:
  - sleep 5
  - psql -c 'create database "userland_test";' -U postgres
  - go get -u -d github.com/golang-migrate/migrate/cmd/migrate
  - cd $GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate
  - git checkout v4.1.0  # e.g. v4.1.0
  - go build -tags 'postgres' -ldflags="-X main.Version=$(git describe --tags)" -o $GOPATH/bin/migrate github.com/golang-migrate/migrate/cmd/migrate
  - migrate -source storage/postgres/migration -database postgres://localhost:5432/userland_test up 2
language: go
go:
  - 1.12.9
env:
  - export GO111MODULE="on"
  - ENV=testing
services:
  - postgresql
  - redis-server
branches:
  only:
  - master
  - travis-ci
sudo: required