before_script:
  - sleep 5
  - psql -c 'create database "userland_test";' -U postgres
  - curl -L https://github.com/golang-migrate/migrate/releases/download/v4.1.0/migrate.linux-amd64.tar.gz | tar xvz
  - ./migrate.linux-amd6 -source storage/postgres/migration -database postgres://localhost:5432/userland_test up 2
language: go
go:
  - 1.12.9
env:
  - GO111MODULE="on"
  - ENV=testing
services:
  - postgresql
  - redis-server
branches:
  only:
  - master
  - travis-ci
sudo: required