version: '3'
services:
  postgres:
    container_name: userland-postgres
    image: postgres:latest
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    container_name: userland-redis
    image: redis:alpine
    ports:
      - 6379:6379